/* 
 * 直接模式
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InlineResponse2001
    /// </summary>
    [DataContract]
    public partial class InlineResponse2001 :  IEquatable<InlineResponse2001>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2001" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse2001() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2001" /> class.
        /// </summary>
        /// <param name="state">响应状态分为：-1,0,1 分别代表响应错误、响应提示、响应成功 (required).</param>
        /// <param name="msg">响应状态为-1时该值为错误信息。响应状态为0时，该值为响应提示信息。响应状态为1时该值为空字符串 (required).</param>
        /// <param name="phone">phone (required).</param>
        /// <param name="virifycodeid">验证码图片的ID值 (required).</param>
        /// <param name="virifyimage">data:image/png;base64 (required).</param>
        /// <param name="confluxaddress">树图区块链地址 (required).</param>
        /// <param name="ethaddress">以太坊、Arbitrum、polygon、BSC等EVM链地址 (required).</param>
        /// <param name="token">用户登录识别令牌，用于后续多个函数的交互，作为输入参数 (required).</param>
        public InlineResponse2001(string state = default(string), string msg = default(string), string phone = default(string), string virifycodeid = default(string), string virifyimage = default(string), string confluxaddress = default(string), string ethaddress = default(string), string token = default(string))
        {
            // to ensure "state" is required (not null)
            if (state == null)
            {
                throw new InvalidDataException("state is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.State = state;
            }
            
            // to ensure "msg" is required (not null)
            if (msg == null)
            {
                throw new InvalidDataException("msg is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.Msg = msg;
            }
            
            // to ensure "phone" is required (not null)
            if (phone == null)
            {
                throw new InvalidDataException("phone is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.Phone = phone;
            }
            
            // to ensure "virifycodeid" is required (not null)
            if (virifycodeid == null)
            {
                throw new InvalidDataException("virifycodeid is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.Virifycodeid = virifycodeid;
            }
            
            // to ensure "virifyimage" is required (not null)
            if (virifyimage == null)
            {
                throw new InvalidDataException("virifyimage is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.Virifyimage = virifyimage;
            }
            
            // to ensure "confluxaddress" is required (not null)
            if (confluxaddress == null)
            {
                throw new InvalidDataException("confluxaddress is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.Confluxaddress = confluxaddress;
            }
            
            // to ensure "ethaddress" is required (not null)
            if (ethaddress == null)
            {
                throw new InvalidDataException("ethaddress is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.Ethaddress = ethaddress;
            }
            
            // to ensure "token" is required (not null)
            if (token == null)
            {
                throw new InvalidDataException("token is a required property for InlineResponse2001 and cannot be null");
            }
            else
            {
                this.Token = token;
            }
            
        }
        
        /// <summary>
        /// 响应状态分为：-1,0,1 分别代表响应错误、响应提示、响应成功
        /// </summary>
        /// <value>响应状态分为：-1,0,1 分别代表响应错误、响应提示、响应成功</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// 响应状态为-1时该值为错误信息。响应状态为0时，该值为响应提示信息。响应状态为1时该值为空字符串
        /// </summary>
        /// <value>响应状态为-1时该值为错误信息。响应状态为0时，该值为响应提示信息。响应状态为1时该值为空字符串</value>
        [DataMember(Name="msg", EmitDefaultValue=false)]
        public string Msg { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [DataMember(Name="phone", EmitDefaultValue=false)]
        public string Phone { get; set; }

        /// <summary>
        /// 验证码图片的ID值
        /// </summary>
        /// <value>验证码图片的ID值</value>
        [DataMember(Name="virifycodeid", EmitDefaultValue=false)]
        public string Virifycodeid { get; set; }

        /// <summary>
        /// data:image/png;base64
        /// </summary>
        /// <value>data:image/png;base64</value>
        [DataMember(Name="virifyimage", EmitDefaultValue=false)]
        public string Virifyimage { get; set; }

        /// <summary>
        /// 树图区块链地址
        /// </summary>
        /// <value>树图区块链地址</value>
        [DataMember(Name="confluxaddress", EmitDefaultValue=false)]
        public string Confluxaddress { get; set; }

        /// <summary>
        /// 以太坊、Arbitrum、polygon、BSC等EVM链地址
        /// </summary>
        /// <value>以太坊、Arbitrum、polygon、BSC等EVM链地址</value>
        [DataMember(Name="ethaddress", EmitDefaultValue=false)]
        public string Ethaddress { get; set; }

        /// <summary>
        /// 用户登录识别令牌，用于后续多个函数的交互，作为输入参数
        /// </summary>
        /// <value>用户登录识别令牌，用于后续多个函数的交互，作为输入参数</value>
        [DataMember(Name="token", EmitDefaultValue=false)]
        public string Token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2001 {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Msg: ").Append(Msg).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Virifycodeid: ").Append(Virifycodeid).Append("\n");
            sb.Append("  Virifyimage: ").Append(Virifyimage).Append("\n");
            sb.Append("  Confluxaddress: ").Append(Confluxaddress).Append("\n");
            sb.Append("  Ethaddress: ").Append(Ethaddress).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2001);
        }

        /// <summary>
        /// Returns true if InlineResponse2001 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2001 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2001 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.Msg == input.Msg ||
                    (this.Msg != null &&
                    this.Msg.Equals(input.Msg))
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                ) && 
                (
                    this.Virifycodeid == input.Virifycodeid ||
                    (this.Virifycodeid != null &&
                    this.Virifycodeid.Equals(input.Virifycodeid))
                ) && 
                (
                    this.Virifyimage == input.Virifyimage ||
                    (this.Virifyimage != null &&
                    this.Virifyimage.Equals(input.Virifyimage))
                ) && 
                (
                    this.Confluxaddress == input.Confluxaddress ||
                    (this.Confluxaddress != null &&
                    this.Confluxaddress.Equals(input.Confluxaddress))
                ) && 
                (
                    this.Ethaddress == input.Ethaddress ||
                    (this.Ethaddress != null &&
                    this.Ethaddress.Equals(input.Ethaddress))
                ) && 
                (
                    this.Token == input.Token ||
                    (this.Token != null &&
                    this.Token.Equals(input.Token))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.Msg != null)
                    hashCode = hashCode * 59 + this.Msg.GetHashCode();
                if (this.Phone != null)
                    hashCode = hashCode * 59 + this.Phone.GetHashCode();
                if (this.Virifycodeid != null)
                    hashCode = hashCode * 59 + this.Virifycodeid.GetHashCode();
                if (this.Virifyimage != null)
                    hashCode = hashCode * 59 + this.Virifyimage.GetHashCode();
                if (this.Confluxaddress != null)
                    hashCode = hashCode * 59 + this.Confluxaddress.GetHashCode();
                if (this.Ethaddress != null)
                    hashCode = hashCode * 59 + this.Ethaddress.GetHashCode();
                if (this.Token != null)
                    hashCode = hashCode * 59 + this.Token.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
